<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tokenresp.proto

namespace Vanguard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>vanguard.AuthenticationResponse</code>
 */
class AuthenticationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>string expiry = 2;</code>
     */
    protected $expiry = '';
    /**
     * Generated from protobuf field <code>uint32 unknown_id = 3;</code>
     */
    protected $unknown_id = 0;
    /**
     * Generated from protobuf field <code>string server_rsa_public_key = 4;</code>
     */
    protected $server_rsa_public_key = '';
    /**
     * Generated from protobuf field <code>repeated bytes signatures = 5;</code>
     */
    private $signatures;
    /**
     * Generated from protobuf field <code>string session_id = 8;</code>
     */
    protected $session_id = '';
    /**
     * Generated from protobuf field <code>uint32 unknown_value = 9;</code>
     */
    protected $unknown_value = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *     @type string $expiry
     *     @type int $unknown_id
     *     @type string $server_rsa_public_key
     *     @type string[] $signatures
     *     @type string $session_id
     *     @type int $unknown_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tokenresp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expiry = 2;</code>
     * @return string
     */
    public function getExpiry()
    {
        return $this->expiry;
    }

    /**
     * Generated from protobuf field <code>string expiry = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExpiry(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->expiry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 unknown_id = 3;</code>
     * @return int
     */
    public function getUnknownId()
    {
        return $this->unknown_id;
    }

    /**
     * Generated from protobuf field <code>uint32 unknown_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUnknownId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->unknown_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string server_rsa_public_key = 4;</code>
     * @return string
     */
    public function getServerRsaPublicKey()
    {
        return $this->server_rsa_public_key;
    }

    /**
     * Generated from protobuf field <code>string server_rsa_public_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setServerRsaPublicKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->server_rsa_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signatures = 5;</code>
     * @return RepeatedField<string>
     */
    public function getSignatures()
    {
        return $this->signatures;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signatures = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSignatures(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->signatures = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session_id = 8;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Generated from protobuf field <code>string session_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 unknown_value = 9;</code>
     * @return int
     */
    public function getUnknownValue()
    {
        return $this->unknown_value;
    }

    /**
     * Generated from protobuf field <code>uint32 unknown_value = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setUnknownValue(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->unknown_value = $var;

        return $this;
    }

}

