<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authentication.proto

namespace Vanguard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>vanguard.AuthenticationRequest</code>
 */
class AuthenticationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string machine_id = 1;</code>
     */
    protected $machine_id = '';
    /**
     * Generated from protobuf field <code>.vanguard.Sub2 field2 = 2;</code>
     */
    protected $field2 = null;
    /**
     * Generated from protobuf field <code>string game_token = 4;</code>
     */
    protected $game_token = '';
    /**
     * Generated from protobuf field <code>string client_rsa_public_key = 5;</code>
     */
    protected $client_rsa_public_key = '';
    /**
     * Generated from protobuf field <code>.vanguard.vg_version version1 = 6;</code>
     */
    protected $version1 = null;
    /**
     * Generated from protobuf field <code>.vanguard.vg_version version2 = 7;</code>
     */
    protected $version2 = null;
    /**
     * Generated from protobuf field <code>string game_id = 8;</code>
     */
    protected $game_id = '';
    /**
     * Generated from protobuf field <code>int32 boot_state = 9;</code>
     */
    protected $boot_state = 0;
    /**
     * Generated from protobuf field <code>repeated string ephemeral_identifiers = 10;</code>
     */
    private $ephemeral_identifiers;
    /**
     * Generated from protobuf field <code>string external_sid = 13;</code>
     */
    protected $external_sid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $machine_id
     *     @type \Vanguard\Sub2 $field2
     *     @type string $game_token
     *     @type string $client_rsa_public_key
     *     @type \Vanguard\vg_version $version1
     *     @type \Vanguard\vg_version $version2
     *     @type string $game_id
     *     @type int $boot_state
     *     @type string[] $ephemeral_identifiers
     *     @type string $external_sid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authentication::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string machine_id = 1;</code>
     * @return string
     */
    public function getMachineId()
    {
        return $this->machine_id;
    }

    /**
     * Generated from protobuf field <code>string machine_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMachineId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->machine_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vanguard.Sub2 field2 = 2;</code>
     * @return \Vanguard\Sub2|null
     */
    public function getField2()
    {
        return $this->field2;
    }

    public function hasField2()
    {
        return isset($this->field2);
    }

    public function clearField2()
    {
        unset($this->field2);
    }

    /**
     * Generated from protobuf field <code>.vanguard.Sub2 field2 = 2;</code>
     * @param \Vanguard\Sub2 $var
     * @return $this
     */
    public function setField2(\Vanguard\Sub2|null $var)
    {
        $this->field2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string game_token = 4;</code>
     * @return string
     */
    public function getGameToken()
    {
        return $this->game_token;
    }

    /**
     * Generated from protobuf field <code>string game_token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGameToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->game_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_rsa_public_key = 5;</code>
     * @return string
     */
    public function getClientRsaPublicKey()
    {
        return $this->client_rsa_public_key;
    }

    /**
     * Generated from protobuf field <code>string client_rsa_public_key = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClientRsaPublicKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client_rsa_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vanguard.vg_version version1 = 6;</code>
     * @return \Vanguard\vg_version|null
     */
    public function getVersion1()
    {
        return $this->version1;
    }

    public function hasVersion1()
    {
        return isset($this->version1);
    }

    public function clearVersion1()
    {
        unset($this->version1);
    }

    /**
     * Generated from protobuf field <code>.vanguard.vg_version version1 = 6;</code>
     * @param \Vanguard\vg_version $var
     * @return $this
     */
    public function setVersion1(\Vanguard\vg_version|null $var)
    {
        $this->version1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vanguard.vg_version version2 = 7;</code>
     * @return \Vanguard\vg_version|null
     */
    public function getVersion2()
    {
        return $this->version2;
    }

    public function hasVersion2()
    {
        return isset($this->version2);
    }

    public function clearVersion2()
    {
        unset($this->version2);
    }

    /**
     * Generated from protobuf field <code>.vanguard.vg_version version2 = 7;</code>
     * @param \Vanguard\vg_version $var
     * @return $this
     */
    public function setVersion2(\Vanguard\vg_version|null $var)
    {
        $this->version2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string game_id = 8;</code>
     * @return string
     */
    public function getGameId()
    {
        return $this->game_id;
    }

    /**
     * Generated from protobuf field <code>string game_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setGameId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->game_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 boot_state = 9;</code>
     * @return int
     */
    public function getBootState()
    {
        return $this->boot_state;
    }

    /**
     * Generated from protobuf field <code>int32 boot_state = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setBootState(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->boot_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ephemeral_identifiers = 10;</code>
     * @return RepeatedField<string>
     */
    public function getEphemeralIdentifiers()
    {
        return $this->ephemeral_identifiers;
    }

    /**
     * Generated from protobuf field <code>repeated string ephemeral_identifiers = 10;</code>
     * @param string[] $var
     * @return $this
     */
    public function setEphemeralIdentifiers(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ephemeral_identifiers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string external_sid = 13;</code>
     * @return string
     */
    public function getExternalSid()
    {
        return $this->external_sid;
    }

    /**
     * Generated from protobuf field <code>string external_sid = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setExternalSid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->external_sid = $var;

        return $this;
    }

}

