<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5ce77708ecf8503e1633946ecf8623bd
{
    public static $files = array (
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' =>
        array (
            'phpseclib3\\' => 11,
        ),
        'P' =>
        array (
            'ParagonIE\\ConstantTime\\' => 23,
        ),
        'G' =>
        array (
            'Google\\Protobuf\\' => 16,
            'GPBMetadata\\Google\\Protobuf\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib3\\' =>
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'ParagonIE\\ConstantTime\\' =>
        array (
            0 => __DIR__ . '/..' . '/paragonie/constant_time_encoding/src',
        ),
        'Google\\Protobuf\\' =>
        array (
            0 => __DIR__ . '/..' . '/google/protobuf/src/Google/Protobuf',
        ),
        'GPBMetadata\\Google\\Protobuf\\' =>
        array (
            0 => __DIR__ . '/..' . '/google/protobuf/src/GPBMetadata/Google/Protobuf',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5ce77708ecf8503e1633946ecf8623bd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5ce77708ecf8503e1633946ecf8623bd::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5ce77708ecf8503e1633946ecf8623bd::$classMap;

        }, null, ClassLoader::class);
    }
}
