<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authentication.proto

namespace Vanguard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>vanguard.vg_version</code>
 */
class vg_version extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 a = 1;</code>
     */
    protected $a = 0;
    /**
     * Generated from protobuf field <code>int32 b = 2;</code>
     */
    protected $b = 0;
    /**
     * Generated from protobuf field <code>int32 c = 3;</code>
     */
    protected $c = 0;
    /**
     * Generated from protobuf field <code>int32 d = 4;</code>
     */
    protected $d = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $a
     *     @type int $b
     *     @type int $c
     *     @type int $d
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authentication::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 a = 1;</code>
     * @return int
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * Generated from protobuf field <code>int32 a = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setA(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 b = 2;</code>
     * @return int
     */
    public function getB()
    {
        return $this->b;
    }

    /**
     * Generated from protobuf field <code>int32 b = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setB(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 c = 3;</code>
     * @return int
     */
    public function getC()
    {
        return $this->c;
    }

    /**
     * Generated from protobuf field <code>int32 c = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setC(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 d = 4;</code>
     * @return int
     */
    public function getD()
    {
        return $this->d;
    }

    /**
     * Generated from protobuf field <code>int32 d = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setD(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->d = $var;

        return $this;
    }

}

